---
- name: Gather Facts from {{ inventory_hostname }} target
  ansible.builtin.setup:
    gather_subset:
      - min
  register: facts

- block:
  # - name: List of debian packages to install
  #   ansible.builtin.debug:
  #     msg: "{{ debian_packages }}"
      
  - name: Installing debian packages
    ansible.builtin.apt:
      force_apt_get: yes
      name: "{{ debian_packages }}"
      state: latest
      update_cache: yes
    retries: 10
    until: result is success or ('Failed to lock apt for exclusive operation' not in result.msg and '/var/lib/dpkg/lock' not in result.msg)
    register: result

  # - name: DEBUG - Installing debian packages
  #   debug:
  #     msg:
  #       - "{{ result }}"

  when: 
    - facts['ansible_facts']['ansible_architecture'] == "x86_64"
    - facts['ansible_facts']['ansible_distribution'] == "Debian"
    - facts['ansible_facts']['ansible_distribution_version'] == "11"

- block:
  # - name: List of fedora packages to install
  #   debug:
  #     msg: "{{ fedora_packages }}"
      
  - name: Installing fedora packages
    ansible.builtin.dnf:
      name: "{{ fedora_packages }}"
      state: latest
      update_cache: yes
  #   register: result

  # - name: DEBUG - Installing fedora packages
  #   debug:
  #     msg:
  #       - "{{ result }}"

  when: 
    - facts['ansible_facts']['ansible_architecture'] == "x86_64"
    - facts['ansible_facts']['ansible_distribution'] == "Fedora"
    - facts['ansible_facts']['ansible_distribution_version'] == "35"
