---
- name: Gather Facts from {{ inventory_hostname }} target 
  ansible.builtin.setup:
    gather_subset:
      - min
  register: facts
  
- when: 
    - facts['ansible_facts']['ansible_architecture'] == "x86_64"
    - facts['ansible_facts']['ansible_distribution'] == "Debian"
    - facts['ansible_facts']['ansible_distribution_version'] == "11"
  block:
    - name: Installing snap packets
      snap:
        name: "{{ item['name'] }}"
        state: "{{ item['state'] }}"
      loop: "{{ snaps_debian }}"
      loop_control:
        label: "{{ item['name'] }} snap is {{ item['state'] }}"
    #   register: result

    # - name: DEBUG - Installing snap packets
    #   debug:
    #     msg: "{{ item }}"
    #   loop: "{{ result['results'] | map(attribute='stdout_lines') | list }}"
