---
- name: List of flatpak packages to install
  debug:
    msg: "{{ packages }}"
    
- name: Installing flatpak packages from flathub
  flatpak:
    name: "{{ packages['flathub'] }}"
    state: present
    method: user
    remote: flathub
#   register: result

# - name: DEBUG - Installing flatpak packages from flathub
#   debug:
#     msg:
#       - "{{ result }}"

- name: Installing flatpak packages from gnome-nightly
  flatpak:
    name: "{{ packages['gnomeNightly'] }}"
    state: present
    method: user
    remote: gnome-nightly
#   register: result

# - name: DEBUG - Installing flatpak packages from gnome-nightly
#   debug:
#     msg:
#       - "{{ result }}"

# - name: Installing flatpak packages from fedora
#   flatpak:
#     name: "{{ packages['fedora'] }}"
#     state: present
#     method: user
#     remote: fedora
#   register: result

# - name: DEBUG - Installing flatpak packages from fedora
#   debug:
#     msg:
#       - "{{ result }}"

# - name: Installing flatpak packages from kdeapps
#   flatpak:
#     name: "{{ packages['kdeapps'] }}"
#     state: present
#     method: user
#     remote: kdeapps
#   register: result

# - name: DEBUG - Installing flatpak packages from kdeapps
#   debug:
#     msg:
#       - "{{ result }}"
