---
- name: Creating additional apt repository files on /etc/apt/sources.list.d/ folder
  apt_repository:
    filename: "{{ item.name }}"
    repo: "{{ item.repository }}"
    state: "{{ item.state }}"
    mode: 0644
    update_cache: no
  loop: "{{ repositories }}"
  loop_control:
    label: "{{ item.name }} repo is {{ item.state }}"    
#  register: result

# - name: DEBUG - Creating additional apt repository files on /etc/apt/sources.list.d/
#   debug:
#     msg:
#       - "{{ result }}"
