---
- name: Check if snapd packet is installed
  debug:
    msg: "{{ snaps}}"
    
- name: Installing snap packets
  snap:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ snaps }}"
  register: result

- name: DEBUG - Installing snap packets
  debug:
    msg: "{{ item }}"
  loop: "{{ result.results | map(attribute='stdout_lines') | list }}"