fedora_users:
  - name: ppacific
    comment: "Paulo Pacifico"
    groups:
      - systemd-journal
      - ppacific
      - docker
      - wireshark
      - libvirt
      - vboxusers
      - plugdev
      - wheel
    state: present
