fedora_users:
  - name: ppacific
    password: "{{ users_password['ppacific'] | password_hash('sha512') }}"
    comment: "Paulo Pacifico"
    groups:
      - systemd-journal
      - ppacific
      - docker
      - wireshark
      - libvirt
      - vboxusers
      - plugdev
      - wheel
    state: present
