---
- name: Ensure storage pools are present
  community.libvirt.virt_pool:
    name: "{{ pool_name }}"
    state: present
    xml: "{{ lookup('file', role_path + '/files/' + pool_name) }}"
  loop: "{{ pool_names }}"
  loop_control:
    loop_var: pool_name

- name: Ensure autostart is enabled
  community.libvirt.virt_pool:
    name: "{{ pool_name }}"
    autostart: true
  loop: "{{ pool_names }}"
  loop_control:
    loop_var: pool_name

- name: Ensure storage is activated
  community.libvirt.virt_pool:
    name: "{{ pool_name }}"
    state: active
  loop: "{{ pool_names }}"
  loop_control:
    loop_var: pool_name
