---
- name: Creating apt keys
  apt_key:
    id: "{{ item.id | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    url: "{{ item.url | mandatory }}"
  when: 
    - item.name != 'puppet'
    - item.name != 'mysql'
    - item.name != 'polychromatic'
  loop: "{{ keys }}"
  loop_control:
    label: "{{ item.name }} key is {{ item.state | default('present') }}"  
#  register: result

- name: Creating apt keys only available from keyservers
  apt_key:
    id: "{{ item.id | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    keyserver: "{{ item.keyserver | mandatory }}"
  when: 
    - item.name == 'puppet' or 
      item.name == 'mysql' or
      item.name == 'polychromatic'
  loop: "{{ keys }}"
  loop_control:
    label: "{{ item.name }} key is {{ item.state | default('present') }}"     
#  register: result

# - name: DEBUG - Creating additional repository files on /etc/apt/sources.list.d/
#   debug:
#     msg:"
#       - "{{ result }}
