debian_users:
  - name: paulo
    comment: "Paulo Roberto"
    groups:
      - cdrom
      - floppy
      - sudo
      - audio
      - dip
      - video
      - staff
      - systemd-journal
      - netdev
      - bluetooth
      - lpadmin
      - scanner
      - paulo
      - docker
      - wireshark
      - libvirt
      - libvirt-qemu
      - vboxusers
      - davfs2
      - plugdev
    state: present

    