---
- ansible.builtin.import_playbook: packageManager.yml

- ansible.builtin.import_playbook: pythonVenv.yml

- ansible.builtin.import_playbook: userManager.yml

- ansible.builtin.import_playbook: libVirt.yml

- ansible.builtin.import_playbook: flatpak.yml

- ansible.builtin.import_playbook: cronTasks.yml

- ansible.builtin.import_playbook: snap.yml